# Site settings
title: NaN
email: sobear.me@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just for fun :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sobear.me" # the base hostname & protocol for your site
twitter_username: imsobear
github_username:  imsobear

excerpt_separator: "<!-- more -->"
permalink: /:categories/:year/:month/:title.html

navigation:
- text: 前端
  url: /front
- text: 生活
  url: /life
- text: 其他
  url: /others
- text: 关于
  url: /about

# Build settings
markdown: redcarpet

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/scss
  style: :compressed # You might prefer to minify using :compressed

