# Site settings
title: 果
email: sobear.me@gmail.com
description: just for fun :)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sobear.me" # the base hostname & protocol for your site

excerpt_separator: "<!-- more -->"
permalink: /:year/:month/:title.html

navigation:
- text: 关于
  url: /about

sns:
- type: github
  name: imsobear
  url: https://github.com/imsobear
- type: twitter
  name: imsobear
  url: https://twitter.com/imsobear
- type: weibo
  name: 帅果同学
  url: http://weibo.com/2808063372/profile


# 友情链接
links:
- text: 荒芜之地
  url: http://darkkate.com/
- text: 一树小草
  url: http://spdf.me/

# Build settings
markdown: redcarpet

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: assets/scss
  style: :compressed # You might prefer to minify using :compressed

